# -*- coding: utf-8 -*-
"""Project Euler: Problem 75

For how many values of L ≤ 1,500,000 can exactly one integer sided
right angle triangle be formed?

https://projecteuler.net/problem=75
"""
from math import sqrt, gcd


def main():
    """Pythagorean triples can be generated by the formulas:
        a = k(m^2 + n^2)
        b = k(2mn)
        c = k(m^2 - n^2)
            Where 0 < n < m
    Knowing that a + b + c = L, we can find that the maximum value of m
    is sqrt(L_max/2)
    """
    L_max = 1500000
    counts = [0] * (L_max + 1)
    for m in range(1, int(sqrt(L_max / 2))):
        for n in range(1, m):
            # M and N have to be coprime and not both odd
            if gcd(m, n) == 1 and not (m % 2 == 1 and n % 2 == 1):
                a, b, c = m ** 2 + n ** 2, 2 * m * n, m ** 2 - n ** 2
                L = a + b + c
                while L < L_max:
                    counts[L] += 1
                    L += a + b + c
    print(sum([c for c in counts if c == 1]))


if __name__ == "__main__":
    main()
